# Generated by Django 2.2.4 on 2019-08-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_LIST', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='element',
            new_name='elements',
        ),
    ]
